---
- hosts: master1:nodes
  gather_facts: False
  tasks:
    - name: Installing nfs-common.
      become: yes
      apt:
          name: nfs-common

- hosts: proxmox
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml

      - name: Add helm nfs-provisioner
        shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

      - name: install helm nfs-provisioner
        shell: |
          helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
          --set nfs.server=nas.devnotnull.com \
          --set nfs.path=/mnt/Tank/proxmox-backup  \
          --set storageClass.defaultClass=true \
          --set storageClass.name=nfs

