apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  selector:
    app: jira
  ports:
  - name: "http-web"
    protocol: TCP
    targetPort: 8080
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: "tcp-postgres"
    protocol: TCP
    targetPort: 5432
    port: 5432
