---
- hosts: hosts
  gather_facts: true
  tasks:
    - name: Including the variables.
      include_vars:
          file: ../../vars.yml

    - name: Performing a Package Upgrade.
      become: yes
      apt:
          name: '*'
          state: latest

    - name: Installing the base packages.
      become: yes
      apt:
          name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'openssl', 'python', 'qemu-guest-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']    
