apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: super-private-pool
      protocol: layer2
      addresses:
      - 10.150.10.100-10.10.10.250
