apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsmaster1
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/NFSPool/k8/jenkins
    server: 10.10.10.50