apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-nodejs.fullname" . }}
  labels:
    {{- include "hello-nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-nodejs.selectorLabels" . | nindent 4 }}

