---
- import_playbook: playbooks/main/deploy_master_vms.yml
- import_playbook: playbooks/main/deploy_minion_vms.yml
- import_playbook: playbooks/main/packages.yml
- import_playbook: playbooks/main/setup_master.yml
- import_playbook: playbooks/main/setup_minion.yml
- import_playbook: playbooks/main/helm.yml
- import_playbook: playbooks/kubernetes/metallb.yml
- import_playbook: playbooks/kubernetes/namespaces.yml
- import_playbook: playbooks/helm/deploy_nfs_provisioner.yml
- import_playbook: playbooks/helm/deploy_longhorn.yml

