apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 10Gi
  volumeName: jira-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-postgres-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 100Gi
  volumeName: jira-postgres-data
