---
- hosts: "{{proxmox}}"
  gather_facts: False
  vars:
  tasks: 
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Stopping the powerdns VMs.
        shell: qm stop {{ hostvars[item].id}}
        with_items:
          - "{{ groups[powerdns] }}"
        ignore_errors: yes

      - name: Destroying the powerdns VMs.
        shell: qm destroy {{ hostvars[item].id}}
        with_items:
          - "{{ groups[powerdns] }}"
        ignore_errors: yes

      - name: Deleting the Resource Pool.
        shell: pvesh delete /pools/{{ resource_pool }}

      - name: Deleting the Ubuntu img image.
        file:
            path: "/tmp/image.img"
            state: absent
        ignore_errors: yes
