---
- hosts: "{{proxmox}}"
  gather_facts: False
  vars:
  tasks: 
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Stopping the master VMs.
        shell: qm stop {{ hostvars[item].id}}
        with_items:
          - "{{ groups[masters] }}"
        ignore_errors: yes

      - name: Stopping the minions VMs.
        shell: qm stop {{ hostvars[item].id}}
        with_items:
          - "{{ groups[minions] }}"
        ignore_errors: yes

      - name: Destroying the master VMs.
        shell: qm destroy {{ hostvars[item].id}}
        with_items:
          - "{{ groups[masters] }}"
        ignore_errors: yes

      - name: Destroying the minions VMs.
        shell: qm destroy {{ hostvars[item].id}}
        with_items:
          - "{{ groups[minions] }}"
        ignore_errors: yes

      - name: Deleting the Resource Pool.
        shell: pvesh delete /pools/{{ resource_pool }}

      - name: Deleting the Ubuntu img image.
        file:
            path: "/tmp/image.img"
            state: absent
        ignore_errors: yes

      - name: Deleting the ~/.kube directory.
        local_action:
            module: file
            path: ~/.kube
            state: absent
        ignore_errors: yes
