---
- hosts: "{{proxmox}}"
  gather_facts: false
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml

      - name: Display all variables/facts known for a host
        debug:
          var: hostvars[groups[masters][0]]

      - name: Creating a resource pool.
        shell: pvesh create /pools -poolid "{{ resource_pool }}" --Comment "Kubernetes Cluster"
        ignore_errors: yes

      - name: Downloading the ubuntu qcow2 image.
        get_url:
            url: "{{ image }}"
            dest: "{{ image_download_location }}image.qcow2"
          
      - name: Creating the VMs.
        shell: >
            qm create {{ hostvars[item].id }}
            --pool {{ resource_pool }}
            --ostype "l26"
            --name {{ hostvars[item].node_name }}
            --description "Kubernetes VM"
            --agent 1
            --cores {{ minion_cpu }}
            --memory {{ minion_mem }}
            --net0 "virtio,bridge={{ bridge }},tag={{ hostvars[item].vlan }}"
            --ipconfig0 "gw={{ hostvars[item].gateway }},ip={{ hostvars[item].ip }}{{ hostvars[item].subnet }}"
            --nameserver {{ hostvars[item].dns }}
            --sshkeys {{ ssh_key }}
        with_items:
          - "{{ groups[masters] }}"

      - name: Importing the qcow2 image as a disk.
        shell: qm importdisk {{ hostvars[item].id }} {{ image_download_location }}image.qcow2 {{ storage }}
        with_items:
          - "{{ groups[masters] }}"

      - name: Configuring the VM Hardware.
        shell: qm set {{ hostvars[item].id }}
               --cipassword password
               --scsihw virtio-scsi-pci
               --scsi0 {{ storage }}:vm-{{ hostvars[item].id }}-disk-0
               --ide2 {{ storage }}:cloudinit
               --boot c --bootdisk scsi0
               --serial0 socket
               --onboot 1
        with_items:
          - "{{ groups[masters] }}"

      - name: Resizing the disk.
        shell: qm resize {{ hostvars[item].id }} scsi0 {{ master_disk }}
        with_items:
          - "{{ groups[masters] }}"

      - name: Starting the VMs.
        shell: qm start {{ hostvars[item].id }}
        with_items:
          - "{{ groups[masters] }}"

      - name: Waiting 2 minutes for for ubuntu to finish booting.
        pause:
            seconds: 120
