---
- hosts: "{{masters}}"
  gather_facts: False
  tasks:            
      - name: Setup masters
        become: yes
        shell: |
          curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server --flannel-backend none