---
- hosts: "{{minions}}"
  gather_facts: False
  tasks:            
      - name: Setup minions
        become: yes
        shell: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" K3S_TOKEN="{{ k3s_token }}" sh -s - --server https://{{ groups[masters][0].ip }}:6443
