---
- hosts: "{{proxmox}}"
  gather_facts: False
  vars:
  tasks: 
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Stopping the master VMs.
        shell: qm stop {{ hostvars[item].id}}
        with_items:
          - "{{ groups[masters] }}"
        ignore_errors: yes

      - name: Destroying the master VMs.
        shell: qm destroy {{ hostvars[item].id}}
        with_items:
          - "{{ groups[masters] }}"
        ignore_errors: yes

      - name: Stopping the minions VMs.
        shell: qm stop {{ hostvars[item].id}}
        with_items:
          - "{{ groups[minions] }}"
        ignore_errors: yes
        register: _stop_instances
        async: 600  # Maximum runtime in seconds. Adjust as needed.
        poll: 0  # Fire and continue (never poll)

      - name: Wait for VM stop job to finish
        async_status:
          jid: "{{ item.ansible_job_id }}"
        register: _jobs
        until: _jobs.finished
        delay: 5  # Check every 5 seconds. Adjust as you like.
        retries: 10  # Retry up to 10 times. Adjust as needed.
        with_items: "{{ _stop_instances.results }}"

      - name: Destroying the minions VMs.
        shell: qm destroy {{ hostvars[item].id}}
        with_items:
          - "{{ groups[minions] }}"
        ignore_errors: yes
        register: _destroy_instances
        async: 600  # Maximum runtime in seconds. Adjust as needed.
        poll: 0  # Fire and continue (never poll)

      - name: Wait for Destroying the minions VMs.
        async_status:
          jid: "{{ item.ansible_job_id }}"
        register: _jobs
        until: _jobs.finished
        delay: 5  # Check every 5 seconds. Adjust as you like.
        retries: 10  # Retry up to 10 times. Adjust as needed.
        with_items: "{{ _destroy_instances.results }}"

      - name: Deleting the Resource Pool.
        shell: pvesh delete /pools/{{ resource_pool }}

      - name: Deleting the Ubuntu img image.
        file:
            path: "/tmp/image.img"
            state: absent
        ignore_errors: yes

      - name: Deleting the ~/.kube directory.
        local_action:
            module: file
            path: ~/.kube
            state: absent
        ignore_errors: yes
