---
- import_playbook: playbooks/main/deploy_img_vms.yml
- import_playbook: playbooks/main/install_base_packages.yml
- import_playbook: playbooks/main/bootstrap_kubernetes.yml
- import_playbook: playbooks/helm/deploy_metallb.yml
# - import_playbook: playbooks/helm/deploy_dashboard.yml

