---
- import_playbook: playbooks/main/deploy_master_vms.yml
- import_playbook: playbooks/main/deploy_minion_vms.yml
- import_playbook: playbooks/main/setup_masters.yml
- import_playbook: playbooks/main/setup_minions.yml
- import_playbook: playbooks/main/helm.yml
- import_playbook: playbooks/helm/deploy_metallb.yml
- import_playbook: playbooks/helm/deploy_nfs_provisioner.yml

