apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
spec:
  rules:
  - host: jenkins.devnotnull.com
    http:
      paths:
        - path: /
          backend:
            serviceName: jenkins
            servicePort: 8080
