---
- hosts: grafana_hosts
  become: true
  gather_facts: true
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_port: 3009
        grafana_security:
          admin_user: admin
          admin_password: password
 
  tasks:
    - name: Including the variables.
      include_vars:
          file: ../../vars.yml
