apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.10.35
    path: "/mnt/NFSPool/k8/jenkins"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-master1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi