apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsmaster1
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/jenkins_master1
    server: 10.10.10.35


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-master1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi