---
- hosts: "{{masters}}"
  gather_facts: false
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Setup masters
        become: yes
        shell: |
          curl -sfL https://get.k3s.io | K3S_TOKEN="{{ k3s_token }}" sh -s - server --disable servicelb

      - name: Fetch .kube/config
        become: yes
        ansible.builtin.fetch:
          src: /etc/rancher/k3s/k3s.yaml
          dest: ~/.kube/config
          flat: yes
