---
- hosts: elk_hosts
  become: true
  gather_facts: true
  roles:
    - role: elastic.elasticsearch
    - role: geerlingguy.logstash
    - role: geerlingguy.kibana
  tasks:
    - name: Including the variables.
      include_vars:
          file: ../../vars.yml
