---
- hosts: elk_hosts
  become: true
  gather_facts: False
  roles:
    - role: mrlesmithjr.elk-kibana
  tasks:
    - name: Including the variables.
      include_vars:
          file: ../../vars.yml
