---
- name: Install logstash
  apt: 
    name: logstash 
    state: present

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/etc/pfelk/conf.d'
    - '/etc/pfelk/databases'
    - '/etc/pfelk/patterns'

- name: Directories Permissions
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - '/etc/pfelk/conf.d'
    - '/etc/pfelk/databases'
    - '/etc/pfelk/patterns'

- name: Copy pfELK Files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: '01-inputs.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '02-types.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '03-filter.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '05-apps.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '20-interfaces.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '30-geoip.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '35-rules-desc.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '36-ports-desc.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '37-enhanced_user_agent.conf', dest: '/etc/pfelk/conf.d/' }    
    - { src: '38-enhanced_url.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '45-cleanup.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '49-enhanced_private.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: '50-outputs.conf', dest: '/etc/pfelk/conf.d/' }
    - { src: 'databases/rule-names.csv', dest: '/etc/logstash/conf.d/databases/' }
    - { src: 'databases/service-names-port-numbers.csv', dest: '/etc/pfelk/databases/' }
    - { src: 'databases/private-hostnames.csv', dest: '/etc/pfelk/databases/' }
    - { src: 'patterns/pfelk.grok', dest: '/etc/pfelk/patterns/' }

- name: Copy logstash configuration
  copy:
    src: "files/pipelines.yml"
    dest: "/etc/logstash/pipelines.yml"
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: yes
